export const categoryTagOptions = [
    { value: 'free', label: 'free' },
    { value: 'tailgate', label: 'tailgate' },
    { value: 'party', label: 'party' },
    { value: 'ufclub', label: 'UF club' },
    { value: 'sports', label: 'sports' },
    { value: 'nightclub', label: 'night club' },
    { value: 'GMB', label: 'GBM' },
    { value: 'gameDay', label: 'game day' },
    { value: 'greek', label: 'greek' },
    { value: 'festival', label: 'festival' },
    { value: 'market', label: 'market' },
    { value: 'groupFitness', label: 'group fitness' },
    { value: 'workshop', label: 'workshop' },
    { value: 'family', label: 'family friendly' },
];
